Add retry test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -25,33 +25,61 @@ build-sha:
     - docker build --pull -t $IMAGE .
     - docker push $IMAGE
 
-test basic:
+# test basic:
+#   stage: test
+#   image: $IMAGE
+#   script: 
+#     - trigger -a $API_TOKEN -p $PROJ_B_PIPELINE_TOKEN -t $REF $PROJ_B_ID
+
+
+# test env variables:
+#   stage: test
+#   image: $IMAGE
+#   script: 
+#     - trigger -a $API_TOKEN -p $PROJ_A_PIPELINE_TOKEN -t $REF -e foo1=bar2 -e foo2=bar3 $PROJ_A_ID
+
+
+# test host & url:
+#   stage: test
+#   image: $IMAGE
+#   script: 
+#     - trigger -a $API_TOKEN -p $PROJ_B_PIPELINE_TOKEN -t $REF -h gitlab.com -u /api/v4/projects $PROJ_B_ID
+
+
+# test detach:
+#   stage: test
+#   image: $IMAGE
+#   script:
+#     - trigger -d -p $PROJ_B_PIPELINE_TOKEN -t $REF $PROJ_B_ID
+
+test retry:
   stage: test
   image: $IMAGE
-  script: 
-    - trigger -a $API_TOKEN -p $PROJ_B_PIPELINE_TOKEN -t $REF $PROJ_B_ID
+  script: |
+    max_retries=10
+    cmd="trigger -d -p $PROJ_RETRY_PIPELINE_TOKEN -t $REF -r $PROJ_RETRY_ID"
 
-
-test env variables:
-  stage: test
-  image: $IMAGE
-  script: 
-    - trigger -a $API_TOKEN -p $PROJ_A_PIPELINE_TOKEN -t $REF -e foo1=bar2 -e foo2=bar3 $PROJ_A_ID
-
-
-test host & url:
-  stage: test
-  image: $IMAGE
-  script: 
-    - trigger -a $API_TOKEN -p $PROJ_B_PIPELINE_TOKEN -t $REF -h gitlab.com -u /api/v4/projects $PROJ_B_ID
-
-
-test detach:
-  stage: test
-  image: $IMAGE
-  script:
-    - trigger -d -p $PROJ_B_PIPELINE_TOKEN -t $REF $PROJ_B_ID
-
+    echo "## Trying until we get first faiure"
+    echo
+    attempt=1
+    until ! $cmd
+    do
+      if (( attempt == max_retries ))
+      then
+            echo "Attempt $attempt failed, retrying ..."
+      fi
+    done
+    
+    echo "## Trying until we get first success"
+    echo
+    attempt=1
+    until $cmd
+    do
+      if (( attempt == max_retries ))
+      then
+            echo "Attempt $attempt failed, retrying ..."
+      fi
+    done
 
 .release_template: &release_template
   stage: release
